### ISSUE TITLE
Request: support for Babel 7?

### ISSUE THREAD

**Issue by albell** [theintern/intern#1087]
Hi, two quick points:

1) I have got this working now, but getting started with this is harder than I thought. All I want to do initially in run some unit tests in node. My project is ES6. Not Typescript. I am not transpiling. The hint about using
```
node: {
    plugins: 'node_modules/babel-register/lib/node.js'
}
```
Could be more front and center. And of course that I now need to create a `.babelrc` with
```
{
    "plugins": [
        "transform-es2015-modules-commonjs"
    ]
} 
```
which isn't mentioned at all. I get that you are trying to keep the setup docs lean, but this is just missing info.

...Which leads me to ...

2) If I were to transpile, I would want to use latest babel, and latest babel plugins etc which is currently: `@babel/plugin-transform-modules-commonjs`.

But that errors out with a message that it doesn't work in the calling context, which is babel 6.*.

*If a Babel 6 environment is a hard requirement please call that out somewhere up front.*

I get that the problems here are non-trivial.  I can't be the only person dealing with this. Because I were transpiling, I definitely would not be using Babel 6, which is a couple years old at this point. Hope this feedback is helpful somehow.

**Comment by jason0x43** [comment]
We could definitely use more direct documentation about how to use Intern in a babel project.

>  And of course that I now need to create a .babelrc with

Intern definitely should work with an _existing_ babel project (which presumably would already have a `.babelrc`), but I'm not sure it should be the responsibility of Intern's documentation to tell a user how to setup a babel project. At least, I would be afraid of getting into a situation where Intern's babel docs fell out of step with actual babel usage.

> 2. If I were to transpile, I would want to use latest babel, and latest babel plugins etc which is currently: @babel/plugin-transform-modules-commonjs.
> 
> But that errors out with a message that it doesn't work in the calling context, which is babel 6.*.

That may be due to a dependency -- Intern doesn't use babel itself, and places no restriction on what version of babel is used by a user project.

> Hope this feedback is helpful somehow.

Feedback is always appreciated! It's very useful to know how developers are using Intern.

**Comment by jason0x43** [comment]
Actually... it's totally reasonable to want to write tests in ES2015+ in a non-ES2015+ project, and there are a couple of ways to do this:

## babel

To use Intern with current babel, you need to:

1. Install `@babel/core`, `@babel/register`, `@babel/preset-env`
2. Create a `.babelrc`
```json
{
  "presets": [ "@babel/env" ]
}
```
3. Add `@babel/register` as a plugin
```json5
// intern.json
{
  "node": { "plugins": "@babel/register" }
}
```

This has been verified to work with Intern 4.8.

## TypeScript

You can use the TypeScript compiler to handle modern JS as well as TypeScript.

1. Install `typescript`
2. Create a `tsconfig.json` file with at least an `allowJs` option
```json
{
  "compilerOptions": { "allowJs": true }
}
```
3. Tell Intern about your `tsconfig` (necessary since the tests won't be `.ts` files)
```json5
// intern.json
{
  "node": { "tsconfig": "tsconfig.json" }
}
```

---

The relevant section of the how_to doc has been updated, and now also includes the TS example.

Closing this since Intern appears to work as expected with babel 7.
