### ISSUE TITLE
Add a performance benchmarking API

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#13]
intern should include a performance/benchmarking API alongside the functional and unit test functionality.  I will re-submit (eventually) my integration of Benchmark.js to provide this API.

**Comment by sholladay** [comment]
FYI, I have posted a rather large bounty for this issue, to help bring it home.
https://www.bountysource.com/issues/1127630-add-a-performance-benchmarking-api

**Comment by kitsonk** [comment]
Thanks for the bounty, and hopefully it will help.  My challenge is that I have zero time to dedicate to this (no matter how emotionally attached to it I am).  If anyone is interested, I would be more than glad to give them my thinking on it.

**Comment by paulirish** [comment]
@sholladay can you describe a little bit about your specific usecases? What sort of performance insight are you looking to gather.

**Comment by sholladay** [comment]
@paulirish, I will tackle that question from a high level.

The following are real use cases for me:

Case 1: I am building [dangit.js](https://github.com/sholladay/dangit "dangit.js - a JavaScript utility library"), a utility library similar in concept to Underscore. That means all the usual with 3rd party JS and needing to be sensitive to the environment. It will run across Node.js and IE9+ (and friends), so engine differences are of note.

From this perspective, I want:
 - Easy to get going. Don't make me read a book, etc. I've got individual public APIs to tweak and I just want to know basic data on how quickly they finish up, given a specific input. I can A/B it live, don't need a ton of history data, etc.
 - Plug and play and config over code. Since it's early days for the project, it will be a pain to work with any additional code required by the performance testing API, So in this case, I'd rather have decisions made for me, and have it "just work" as much as possible, at the cost of flexibility I would desire in a later stage project.

Case 2: I work on [sitecues](https://www.sitecues.com "sitecues by Ai Squared, zoom and speech for websites"), a fairly mature project with a stable architecture. It's browser only and relies heavily upon the latest graphics and animations tech on the web to do deceptively simple things like throw up lightboxes. Which of course, doesn't always go as smoothly as we all would like.

From this perspective, I want:
 - Easy to package and deploy the results and compare them across time. So give me JSON or directories with minimal clutter for gzipping, etc. I won't be too picky on the exact format, but it must be easy to serialize. We archive, transfer across servers, typical company stuff. Here, I don't mind consuming and presenting the data myself.

**Comment by paulirish** [comment]
Gotcha. thanks very much for the use cases. In both of those cases it seems like you want to know about your costs so anything out of the ordinary stands out, and then monitor those over time for regressions.

"Benchmarking" these would mean isolating each test into something benchmarky, [fixing it up so it's not written poorly](http://www.slideshare.net/mathiasbynens/using-jsperf-correctly), and running it in tight, heavy loops.

I think what we want is continuous performance measurement. We want a profiler to run against your tests and tell you about how you're doing when its run like a real user, not like a user who runs `util.deepCopy` 100,000,000 in a row.  

I put out some ideas here: https://github.com/paulirish/automated-chrome-profiling#readme  Take a look. Having this performance data for your intern-driven tests would give you a heck of a lot of insight.

**Comment by kitsonk** [comment]
Ok, I am starting to pick this back up...  It has been bouncing around my head for far too long.

## Story

As a developer, I want to be able to baseline the performance of my code for two purposes:

* To ensure that when given a problem, I can test to see which ways of solving the problem are most performant.
* To ensure that once I have a set of code, as I perform continuous integration, that my code does not degrade unacceptably in performance.

## API

I am thinking we need to add `BenchmarkSuite`, a `benchmark` interface and a `BenchmarkBaseline` and `Benchmark` reporters.

The `BenchmarkSuite` will allow you to assert tests that will be run within the benchmarking environment and deal with exposing the performance data returned from a run.  The `benchmark` interface will allow easy creation of test suites that do benchmarking.  The `BenchmarkBaseline` reporter will output a set of results given a `benchmark` suite which can be then consumed by the `Benchmark` reporter to determine if your benchmarking suites are "passing" or "failing" your benchmarks.

Obviously the "success" or "fail" criteria could be manually expressed too, to be consumed by the `Benchmark` reporter.

## To Do

I will be working on this in [kitsonk/intern#benchmark](https://github.com/kitsonk/intern/tree/benchmark).

- [ ] Integrate Benchmark.js
- [ ] BenchmarkSuite
- [ ] benchmark Interface
- [ ] BenchmarkBaseline reporter
- [ ] Benchmark reporter
- [ ] Documentation

**Comment by kitsonk** [comment]
Ok, I have a working prototype now.  I think I have the workflow right in my mind, but feedback would certainly help me.  Here is what I see the main use case/workflow:

1. Write benchmark tests, using the benchmark interface.  The would be the key performance areas that you want to benchmark.
1. Baseline your tests.  The `BenchmarkBaseline` reporter will collect the performance benchmarks (ops/sec) from all the environments you have listed.  It then can write these to a JSON file which will be used as your baseline.  The baseline file will also contain the acceptable level of variance and change to warn and fail on.
1. Execute your benchmarks.  Given a baseline file, when you run your benchmark tests, they will warn or fail if the variance falls outside of the thresholds.

The other main use case is just a plain Benchmark report, which would give you detailed information about your Benchmark tests.  I need to do more work on this, but I was thinking it would generate an HTML report that would do the following:
* Provide you with performance information by environment.
* Provide you with visual comparison of the performance by test, by environment.

**Comment by sholladay** [comment]
Thank you for all of the hard work on this, @kitsonk. Seems reasonable to me.

I'm wondering if you can outline how baselining might work. In my mind, this is one of the most important pieces. Any given test run can be a fluke (especially for functional tests), so I feel like it makes sense to baseline from an average of say 3 runs, with the user confirming the result is reasonable. It seems like a very interactive story. Or maybe this is a higher level than Intern ought to provide.

**Comment by kitsonk** [comment]
[benchmark.js](http://benchmarkjs.com/) tries its best to deal with those "flukes" and isn't necessarily designed for long running benchmarking of functional tests.  It does allow you to increase the run window (defaulting to 5 seconds) if you have a particular challenging test that is providing inconsistent results.  But in the end it is designed for very small units of code, not some sort of end to end integration test.  I would also say in practice that is the best way to do it, measure a lot of little points looking for regressions in performance.

Every test run emits two important numbers, the first is the cycles per second, the second is the relative margin of error.  If the RME is too large, then it is a sign that you are not getting an accurate number.  What I have been working on is that the baseline will be emitted for each test in each environment configured.  There will be some default "warn" and "error" thresholds.  If you are benchmarking against a baseline then variations of the CPS or RME outside of those thresholds will warm/error.  The baseline file will be just a JSON file and can be edited if the human knows best.

If you just want to track performance over a period of time, then you would need something external to aggregate the benchmarking reports and do some sort of tracking.

**Comment by kitsonk** [comment]
I have migrated my personal branch (with the contributions from @jason0x43) from my personal repo to the [benchmark](theintern/intern/tree/benchmark) branch.  I merged in the latest master, but the Benchmark.js and lodash dependencies need a bit of updating.

**Comment by jason0x43** [comment]
Added in Intern 3.4
