### ISSUE TITLE
Document 'webdriver' object in the config

### ISSUE THREAD

**Issue by necolas** [theintern/intern#266]
It's not included in https://github.com/theintern/intern/wiki/Configuring-Intern

**Comment by cloudbring** [comment]
It would be great to have a webdriver config option. I would like to be able to change the port and host. This would allow me to have a local selenium server running for developing and debugging tests locally while being able to run my cloud configs periodically to validate.

*I cannot do that now because the webdriver defaults to connecting the Selenium server on port `4444` both for local development and for remote/cloud configs*. This means I have stop my local selenium-server manually before running the could configs. This would be really helpful for my workflow.

**Comment by csnover** [comment]
@cloudbring please see the `tunnelOptions` configuration setting, which already does what you want.

**Comment by cloudbring** [comment]
Thank you! Works like a charm!
