### ISSUE TITLE
Provide a way to automate running unit tests that does not require Selenium or SauceLabs

### ISSUE THREAD

**Issue by tomwayson** [theintern/intern#314]
I'd like to be able to run my unit tests continuously in multiple browsers as I modify my code, the way I can w/ Karma, and by that I mean w/o having to run a local standalone selenium server or to upload our code to SauceLabs in order to do so.

For a concise example of why I think it's a bad idea to _require_ selenium to automate running the unit tests, see this PR:

https://github.com/xsokev/Dojo-Bootstrap/pull/150

1) I wanted to update to Intern 2.1 (https://github.com/xsokev/Dojo-Bootstrap/issues/144)
2) In the process, I noticed that tests no longer ran in FF (https://github.com/xsokev/Dojo-Bootstrap/issues/145) due to [a FF driver bug introduced when evergreen FF updated itself to v 32](https://code.google.com/p/selenium/issues/detail?id&#61;7642)
3) That bug was fixed w/ an update to Selenium 2.43, but that [caused the grunt task I used to launch Selenium not to work](https://github.com/BrianBunker/grunt-se-launch/issues/3), so I swapped that out w/ another one
4) In the process of testing that I noticed that tests stopped running in Safari - now it looks like there's an [issue w/ Safari driver](https://code.google.com/p/selenium/issues/detail?id&#61;7933) after updating Safari 

Add all that to the fact that I still have never gotten the IE driver to run on my PC, and you can see why I want to limit my dependence on Selenium to only what I absolutely need it for - functional tests.

I recognize that none of these issues are w/ the Intern itself, but rather w/ it's dependency on Selenium to automate running the unit tests. I know from looking at other issues in this repo and all threads on the Selenium forum that I'm not only person that has these issues w/ Selenium and it's launchers and browser drivers.

Re: Sauce Labs, I can't ever imagine that being the only place I run my unit tests, as they are so intertwined w/ my development process. I need them to run in a couple of seconds, not minutes, so that's a not a solution for this issue.

I guess I could wire up livereload to continuously reload client.html, but it would be nice if the Intern shipped w/ a way for me to achieve what I get w/ Karma w/o having to do all that myself for each project.

**Comment by mightyiam** [comment]
Apart from the specific issues that @tomwayson had with some selenium versions, I can honestly reiterate both his original report and his response almost word for word.

@csnover thank you for your response.

I absolutely love the way Karma launches browsers and reruns my tests on detected changes.

I can set up livereload quite easily but is there any way that I would get console output for the tests on my terminal?

**Comment by dylans** [comment]
Reading through https://karma-runner.github.io/0.12/intro/how-it-works.html and https://github.com/karma-runner/karma/raw/master/thesis.pdf (the university thesis behind karma), basically this is what they are doing via a Node.js server:

* Serve tests to browsers within a test runner
* Collect test results from clients
* Open web browsers and run tests
* Automatically run tests again if files change within a project
* If browser is already open and running tests, tell the browser to rerun the tests when files change (uses WebSockets to communicate to the open clients)
* Made attempts to solve a few other problems along the way (DI, mocks, etc.)

Perhaps a few shortcuts to get some of the things that Intern doesn't do today would be as follows, and perhaps make this easier for someone in the community to contribute to (as it could probably just be done as a few grunt tasks with the existing code, and there are already well established watch tasks with Grunt: https://github.com/gruntjs/grunt-contrib-watch ):

* Grunt task to watch for changed files and run unit tests in all browsers listed within your Intern config by opening the browsers, and running intern, e.g. http://localhost:9001/__intern/client.html?config=foo
* Grunt task to watch for changed files and run unit+functional tests in all browsers listed within your Intern config by running intern-runner
* While useful, lower priority because there are so many other tools to do this already: A new reporter that can collect and aggregate tests results from many tests runs over time, rather than for just a single test run, so you can see regressions over time

**Comment by mightyiam** [comment]
Thank you, @dylans.
I'm not sure whether your suggestions include in some way the printing of test reports to the console.

**Comment by dylans** [comment]
> I'm not sure whether your suggestions include in some way the printing of test reports to the console.

One way I see to make that work with pure unit tests is to log the results to the server, which then returns those results to the console tab where the grunt task is running. I don't see a way to simply have a task to open a browser and return console results to it, without logging the results somewhere first.

**Comment by mightyiam** [comment]
Thank you, @dylans.

**Comment by sholladay** [comment]
Presumably you are looking for something like this? https://github.com/benderjs/browser-launcher2

I wonder if there would be a non-terrible way of doing this mostly in user-land, with only minor tweaks on a fork of Intern, as a proof of concept. That theory is based on the fact that, from what I've seen, Intern doesn't make too many assumptions about how the session gets started (for unit tests).

**Comment by jason0x43** [comment]
There is now some support for this with [intern-cli](https://github.com/theintern/intern-cli). You can run `intern serve -o` to start the Intern proxy server and automatically open the system-default browser to the `client.html` test page.

**Comment by indolering** [comment]
I came here with a similar request, to run unit tests in real a real browser in the background.

Coming from Polymer and their excellent WebComponentTester, I really enjoyed the ability to run unit tests in the browser.  Intern could match the UX of running unit tests in Node by controlling a Selenium standalone server running the (upcoming) headless version of Chrome.  

I agree that moving away from Selenium would be a bad idea for all of the reasons outlined above.  Based on the summary about Karma's internals, the problem isn't with Selenium per se, but its focus on end-to-end functional testing.  If anything, we should be pushing upstream Selenium to provide similar features.

**Comment by mightyiam** [comment]
This issue inspired me write a little post just now:
https://medium.com/@mightyiam/why-in-browser-unit-testing-is-declining-c0a7b14f60bf#.loyksxqwg

**Comment by dylans** [comment]
As noted earlier by @jason0x43, intern-cli now helps quite a bit with this. Also, Intern's SeleniumTunnel will now make sure you have a local copy of all of the Selenium Driver dependencies that you need to run your tests. So I think we're just about there with regards to the use case of the original request, with the exception of having a watch task to auto test things (either rerun all tests, or rerun tests only for tests related to modules that have changed).

**Comment by indolering** [comment]
Firefox and Chrome have both announced headless modes.  Supporting this in the future should be as simple as altering the command used to launch Chrome.

Lock thread?

**Comment by jason0x43** [comment]
Headless mode is going to be great, but it won't eliminate the need for Selenium. Selenium isn't just used for functional tests, it's what enables Intern to start up and manage browsers. Intern-cli provides a very basic method for _starting_ browsers without Selenium, but it's fairly limited. For more complete Selenium-free functionality, we would need to add a new tunnel type to Dig Dug, or make a new plugin entirely, that can manage browsers without Selenium.

**Comment by jason0x43** [comment]
I'm closing this in favor of https://github.com/theintern/digdug/issues/54 (Dig Dug is where this feature will eventually be implemented).
