### ISSUE TITLE
intern-runner does not appear to be able to communicate with Firefox 35

### ISSUE THREAD

**Issue by mgingras** [theintern/intern#333]
intern-runner hangs when running tests against Firefox 35, using Selenium 2.44

The following error appears in the console:

```
  Security wrapper denied access to property push on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.
 
  Error: Permission denied to access property '0'
```

**Comment by jason0x43** [comment]
I've also experienced this. The problem is most likely an incompatibility between FF 35 and Selenium, which Intern uses to manage browsers. Occasionally a new Firefox will be incompatible with the current version of Selenium. The solution in that case is to use keep using a compatible version of Firefox until a new Selenium version is released.

**Comment by csnover** [comment]
Presumably the same as this report, https://code.google.com/p/selenium/issues/detail?id=8387

**Comment by csnover** [comment]
Selenium 2.45.0 is finally released with support for Firefox 35+.
