### ISSUE TITLE
DOCS: running functional tests (selenium webdriver based) with local browsers

### ISSUE THREAD

**Issue by ainthek** [theintern/intern#347]
I have spent some time reading docs, and even with my skils from other environments (selenium-webdriver, karma) I had no success to make trivial SELENIUM based test to run.

sample: browse google.com and execute query in local Chrome.

I have even downloaded finsied tutorial and functionalSuites seem to ignored from config and comd line params. Only suites are run. 

Is there any quick guide to make functionalSuites run localy ? Thanx a lot.

**Comment by jason0x43** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

Make sure you're using `intern-runner` to run your tests and not `intern-client`, since `intern-client` will only run unit tests.

Thank you again for your interest!

**Comment by ainthek** [comment]
thanx a lot. will follow the guideline. anyway will search for docs am sure i have seen intern-client + suites in one of the docs.

**Comment by jason0x43** [comment]
intern-client will only run suites; intern-runner runs both suites and functional suites.
