### ISSUE TITLE
0/0 tests failed (false passing)

### ISSUE THREAD

**Issue by mightyiam** [theintern/intern#352]
I'm having false passing tests, such as [this](https://travis-ci.org/mightyiam/edited/builds/50846160).

Just search the log for `0/0`.

Does anyone have any idea why this could occur, please?

**Comment by csnover** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

Thank you again for your interest!
