### ISSUE TITLE
Auto-glob in Node.js

### ISSUE THREAD

**Issue by csnover** [theintern/intern#359]
When running in Node.js, we have filesystem access, so should allow glob patterns in `suites` and `functionalSuites` for users that don’t ever run tests directly in the browser.

**Comment by sholladay** [comment]
+1, I would really appreciate this. The workarounds for this are messy.

**Comment by sholladay** [comment]
For the case of unit tests in the browser, what if there were simply a requirement that the Intern proxy be running in order to use glob patterns, which could provide a service route for retrieving data about the filesystem.

So as a user I do something like:
````
node node_modules/.bin/intern-runner config=tests/intern proxyOnly
````
... then visit ...
````
http://localhost:9000/__intern/client.html?config=tests/intern
````

This already works and I do it pretty regularly to use `client.html` since it means I don't need to host my own server. So all we have to do is ask `localhost:9000/__intern/suites.json?glob=*/*` or whatever to please send us a list.

**Comment by jason0x43** [comment]
I just submitted a PR for this if anyone would like to review. It resolves globs in the suites and functionalSuites lists in both the browser and node context. The browser context, of course, assumes you're using Intern's proxy.
