### ISSUE TITLE
why the command is not reconized

### ISSUE THREAD

**Issue by bogatisuman** [theintern/intern#361]
I have installed **intern** both locally and globally but the **inern --version** command is not working.

Why is it so? For more information please have a look [the stackoverflow post] (http://stackoverflow.com/questions/28924906/how-do-i-confirm-intern-is-installed)

**Comment by csnover** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

Thank you again for your interest!
