### ISSUE TITLE
Is Intern going to move to ES6 modules?

### ISSUE THREAD

**Issue by httpete** [theintern/intern#363]
I notice that the code sample demos in the doc are using a different sort of way to use require, defining the amd and then using a require('module') inside. Why this change and should we expect intern to move from AMD to ES6?

I think it's fair to say that AMD is going to be replaced by ES6 Modules.

**Comment by csnover** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

The information you are requesting is also already in the user guide under the [section on conventions](https://theintern.github.io/intern/#conventions).

Thank you again for your interest!
