### ISSUE TITLE
reporters=webdriver

### ISSUE THREAD

**Issue by engine07** [theintern/intern#364]
Hi,

Would appreciate small help with following.

While doing  tests  with runType: 'runner' , which expect some dom manipulation in browser
I had issue with default webdriver reporter which I cannot find a way to switch off.

For example, have a code which check if dom element is in viewport.
Want to test this code against many browsers using selenium.
My attempt was to create dom elements from inside test script
and then assert against result from code under a test.
But because of webdriver reporter, I cannot do so because
it also manipulate dom and scrolls page to bottom after each test.
So if I was to create dummy page inserted inside a test which has long scroll
and one div on bottom and if wanted to test that this this is not in viewport, cannot do it.

if I could switch off webdriver reporter this would not be issue
but still not sure if this is possible nor if this would make any issues
for running tests on saucelabs through selenium.

Am I doing it wrong way or..?

**Comment by csnover** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

Thank you again for your interest!
