### ISSUE TITLE
There is no scrollIntoView function

### ISSUE THREAD

**Issue by vionemc** [theintern/intern#366]
I think it is a very important function.
I've tried using `moveMouseTo` but it causes weird error on the HTML. I can't find any element because of it.

**Comment by sholladay** [comment]
Some actions, such as `click()`, cause [scroll to happen](http://stackoverflow.com/questions/3401343/scroll-element-into-view-with-selenium#3403683 "Source for assertion that the click method causes scroll to happen under the hood.") implicitly. If that doesn't cover your use case, you can run any JavaScript you want in the browser itself by using the [execute()](https://theintern.github.io/leadfoot/Command.html#execute "Documentation for Leadfoot's execute method.") or [executeAsync()](https://theintern.github.io/leadfoot/Command.html#executeAsync "Documentation for Leadfoot's executeAsync method.") methods. Meaning, you can use the browser's native [scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView "Documentation for native browser scrollIntoView() method, on MDN.").

Also, these commands are the responsibility of [Leadfoot](https://github.com/theintern/leadfoot "Project page for Leadfoot."), which Intern simply uses under the hood, But it is a standalone project, with its own issue tracker.

**Comment by csnover** [comment]
We are happy to consider new features that make life easier for Intern users, though as noted by @sholladay you may already call the `scrollIntoView` function yourself today with `execute`, and interaction functions that require scrolling will implicitly perform the scroll for you, so it sounds like this is probably due to some other issue with your tests.

Because “weird error on the HTML” isn’t enough information for us to start troubleshoot any problem you are having, I am going to close this ticket for now. If you are continuing to experience a problem please definitely [post about it on Stack Overflow](http://stackoverflow.com/questions/ask?tags=intern) for us to take a look at. If you would like I can also create an enhancement request for this API in the [Leadfoot project](https://github.com/theintern/leadfoot), let me know if this would be useful. Thanks!
