### ISSUE TITLE
Help required to get functional testing to work

### ISSUE THREAD

**Issue by andywillis** [theintern/intern#370]
Hi. I'm trying to get functional testing to work through Intern but I'm running into problems both with PhantomJS and SauceLabs. I'm working on a Mac Yosemite using [this patched version of PhantomJS](https://github.com/eugene1g/phantomjs/releases).

In short the error I'm getting for both is:
> undefined: Cannot find the Node.js require at http://localhost:9000/__intern/node_modules/dojo/node.js:6:3
> No stack or location

My question: am I doing something stupid to prevent this from working?

Here is my SauceLab config file:
```javascript
define({
  proxyPort: 9000,
  proxyUrl: 'http://localhost:9000/',
  capabilities: {
    'selenium-version': '2.41.0'
  },
  environments: [
    { browserName: 'internet explorer', version: '11', platform: 'Windows 8.1' },
    { browserName: 'internet explorer', version: '10', platform: 'Windows 8' },
    { browserName: 'internet explorer', version: '9', platform: 'Windows 7' },
    { browserName: 'firefox', version: '28', platform: [ 'OS X 10.9', 'Windows 7', 'Linux' ] },
    { browserName: 'chrome', version: '34', platform: [ 'OS X 10.9', 'Windows 7', 'Linux' ] },
    { browserName: 'safari', version: '6', platform: 'OS X 10.8' },
    { browserName: 'safari', version: '7', platform: 'OS X 10.9' }
  ],
  maxConcurrency: 3,
  tunnel: 'SauceLabsTunnel',
  tunnelOptions: {
    username: 'xxx',
    accesskey: 'xxx'
  },
  useLoader: {
    'host-node': 'dojo/dojo',
    'host-browser': 'node_modules/dojo/dojo.js'
  },
  loader: {
    // Packages that should be registered with the loader in each testing environment
    packages: [ { name: 'myPackage', location: '.' } ]
  },
  reporters: 'runner',
  functionalSuites: [
    'test/functional/test'
  ],
  excludeInstrumentation: /^(?:test|node_modules)\//
});
```
and my functional test is:

```javascript
define(function (require) {
  var registerSuite = require('intern!object');
  var assert = require('intern/chai!assert');
  registerSuite({
    name: 'hello',
    greet: function () {
      assert(1, 1, 'same');
    }
  });
});
```

**Comment by jason0x43** [comment]
Thanks for writing!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

That said...

The error you're seeing generally indicates that you're trying to load a node module in the browser with `dojo/node`. Nothing in the config you've posted is doing that, and it works fine when I run it on my system. The only issue I see is that your `assert` syntax is off (it should be `assert(expression, message)`), but that's not going to cause the error you're seeing.
