### ISSUE TITLE
Comparison table corrections

### ISSUE THREAD

**Issue by elhigu** [theintern/intern#376]
Hi, looks like there is still some misinformation in comparison table:

"Runs stand-alone2 in browsers" - Also karma supports running tests by navigating to url, by default port in 9018

"Can be used with any4 assertion library" - As far as I know Jasmine does not limit choice of assertion library either. 

"Lets you write your own custom reporters" - You can write own reporters or use 3rd party reporters for results collected by karma.

**Comment by csnover** [comment]
> "Runs stand-alone2 in browsers" - Also karma supports running tests by navigating to url, by default port in 9018

This requires you to run a special Karma server which means it is not usable stand-alone, it requires Node.js and other stuff on the server in order to run. Intern doesn’t need anything but your own Web server for basic unit testing in a browser.

> "Can be used with any4 assertion library" - As far as I know Jasmine does not limit choice of assertion library either. 

Jasmine’s internal assertion mechanism does not use errors for test result control, it uses calls to `addExpectationResult`, so you can’t just swap out a different assertion library and have everything work the same as it would if you use Jasmine’s built-in `expect` method (you will, at least, lose expected/actual details).

> "Lets you write your own custom reporters" - You can write own reporters or use 3rd party reporters for results collected by karma.

Thanks, this is updated.
