### ISSUE TITLE
JUnit reporter swallows non-test-related output

### ISSUE THREAD

**Issue by alekstorm** [theintern/intern#389]
Recently, I ran out of minutes on Sauce Labs. Since I was running with `reporters=junit`, there was zero console output, but since the tests never even started to run, no `report.xml` was generated. I had to log in to Jenkins and run the command manually with the default reporter to see the error.

I'm not sure whether error output like this should go to the console or `report.xml`, but it definitely should end up *somewhere*.

**Comment by csnover** [comment]
Just to make sure… are you aware you can use more than one reporter simultaneously, so you could use one of the other reporters to output this information too (like to the console)?

**Comment by alekstorm** [comment]
Well, that definitely solves my problem. Thanks!

**Comment by csnover** [comment]
OK, since that fixes this issue for you I will close this ticket. The JUnit format doesn’t provide a way to indicate that there was a fatal error like this that prevented the test system from running at all. If someone wants to try to wedge it in (like by outputting suites on a fatal error) I’m happy to accept a pull request but I don’t think the Intern team would commit to doing that work.
