### ISSUE TITLE
Intern 3: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#409]
Got a repro case here: https://github.com/vladikoff/intern-quick-test/tree/maxStack

```
➜  intern-quick-test git:(master) ✗ npm test

> intern-quick-test@1.0.0 test /Users/vladikoff/dev/intern-quick-test
> intern-runner config=intern

RangeError: Maximum call stack size exceeded
No stack or location
npm ERR! Test failed.  See above for more details.
```

Running throws an error: 
```
 node_modules/.bin/intern-runner config=intern
```

But this works:
```
➜  intern-quick-test git:(maxStack) node_modules/.bin/intern-runner config=intern.js
Listening on 0.0.0.0:10232
Tunnel started
‣ Created session firefox on any platform (e517b468-3d08-4b4c-8d3a-61dcccf79808)
✓ firefox on any platform - unit tests - test1 - testTrue (0.001s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/1 tests failed


TOTAL: tested 1 platforms, 0/1 tests failed
```

**Comment by csnover** [comment]
`config` is a module ID. When you specify `intern` as the module ID of the configuration file, this conflicts with the `intern` package which is already registered and causes `node_modules/intern/main.js` to be loaded instead. I’m investigating just resolving the full path explicitly when retrieving the config since the module ID-ness of the config argument seems to baffle most.
