### ISSUE TITLE
Intern 3: "Node.js hang detected;" appears in the terminal after tests are terminated wit ^C

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#410]
I started running the tests and stopped after a few tests passed with ^C.
I then started running other commands in the terminal, but then suddenly got `Node.js hang detected; make sure to close all sockets, timers, and servers you opened during testing!` in the terminal window.

### output

【 code  】
➜  fxa-content-server git:(intern3-try2) ✗ npm run test-latest

> fxa-content-server@0.39.0 test-latest /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional_full fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaEmailRoot=http://restmail.net fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaIframeOauthApp=https://123done-latest.dev.lcip.org/iframe fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaProduction=true fxaToken=https://token.dev.lcip.org/1.0/sync/1.5

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
Node.js hang detected; make sure to close all sockets, timers, and servers you opened during testing!
‣ Created session firefox on any platform (ba786964-3baa-40b3-9e13-f3b6a017d850)
✓  firefox on any platform - refreshing a screen logs a refresh event - refreshing the signup screen (2.822s)
✓  firefox on any platform - sign_in - sign in unverified (2.432s)
Waiting for email at: http://restmail.net/mail/signin0.2526841014623642
✓  firefox on any platform - sign_in - sign in verified with correct password (4.284s)
Waiting for email at: http://restmail.net/mail/signin0.2526841014623642
✓  firefox on any platform - sign_in - sign in verified with incorrect password, click `forgot password?` (3.252s)
✓  firefox on any platform - sign_in - sign in with an unknown account allows the user to sign up (1.726s)
Waiting for email at: http://restmail.net/mail/signin0.2526841014623642
✓  firefox on any platform - sign_in - sign in with email with leading space strips space (3.677s)
Waiting for email at: http://restmail.net/mail/signin0.2526841014623642
✓  firefox on any platform - sign_in - sign in with email with trailing space strips space (3.56s)
Waiting for email at: http://restmail.net/mail/signin0.2526841014623642
✓  firefox on any platform - sign_in - sign in verified with password that incorrectly has leading whitespace (3.23s)
^C
Shutting down gracefully; please wait or hit CTRL+C again to quit immediately
✓  firefox on any platform - sign_in - visiting the pp links saves information for return (0s)
No unit test coverage for firefox on any platform 
firefox on any platform: 326/335 tests failed

TOTAL: tested 1 platforms, 326/335 tests failed
➜  fxa-content-server git:(intern3-try2) ✗ git diff
.... STUFF HERE ....
➜  fxa-content-server git:(intern3-try2) gNode.js hang detected; make sure to close all sockets, timers, and servers you opened during testing!
【 end code 】

**Comment by csnover** [comment]
Whatever shell you are using is probably responsible for detaching the process at the time the first signal is sent, this behaviour does not occur in bash (and can’t actually occur unless it’s the shell’s fault, the Intern process has obviously not terminated or closed stdout/stderr or else it would not be able to write that message later).

If you could, please [use the template](https://github.com/theintern/intern/issues/new?body=Description:%0A%0ASteps+to+reproduce:%0A%0A1.%20%E2%80%A6%0A2.%20%E2%80%A6%0A3.%20%E2%80%A6%0A%0AExpected%20result:%0AActual%20result:%0A%0AIntern%20version:%0A%0AAny%20additional%20information:), I am having to make too many guesses and assumptions in your current tickets because I don’t have enough information to go off of. Thanks!

**Comment by csnover** [comment]
I’ve seen this happen from time to time; what it usually means is that the cancellation caused the `Executor#run` promise to resolve before the executor has actually finished cleaning up, so the hung code system activates and thinks the normal shutdown process is hanging (it isn’t, it’s just slow as F sometimes because it waits for the WebDriver server to respond to a `quit` message). I need to figure out what needs to be done, but since this is largely a cosmetic issue it will probably be deferred to a point release.

**Comment by jason0x43** [comment]
I believe the causes of this (hanging server connections, unresolved promises, non-canceled timeouts) have been resolved at this point. If this comes up again, we can reopen this issue or start a new one.

**Comment by jason0x43** [comment]
Well, start a new one since this is for Intern 3. :)
