### ISSUE TITLE
Intern 3: Default reporter is not coloring 'error output' properly

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#411]
### Current with `master` Intern 3

![](http://v14d.com/i/5579c6ddc1810.png)

### Intern 2

![](http://v14d.com/i/5579c70266eee.png)

Does this mean it is not piping into stderr or something?

**Comment by csnover** [comment]
The Runner reporter is actually more colourful now but whatever you are using doesn’t comprehend the ANSI escape codes. It is currently intentional that all output is sent to a single output stream for implementation simplicity and consistency.

As with the last ticket I would really appreciate it if you could use [the template](https://github.com/theintern/intern/issues/new?body=Description:%0A%0ASteps+to+reproduce:%0A%0A1.%20%E2%80%A6%0A2.%20%E2%80%A6%0A3.%20%E2%80%A6%0A%0AExpected%20result:%0AActual%20result:%0A%0AIntern%20version:%0A%0AAny%20additional%20information:) from the contribution guide so I can understand more easily and potentially reproduce what exactly is the problem. Thanks!

**Comment by vladikoff** [comment]
This should be fixed in TeamCity 9.1 : https://confluence.jetbrains.com/display/TW/Hajipur+9.1+EAP2+%28build+36518%29+Release+Notes#Hajipur9.1EAP2%28build36518%29ReleaseNotes-ANSIstylecoloringinbuildlogs

**Comment by csnover** [comment]
Great! I like it when things fix themselves. :)
