### ISSUE TITLE
Alameda as a loader doesn't work, tries to load "undefined.js".

### ISSUE THREAD

**Issue by httpete** [theintern/intern#436]
if I load require.js for host-browser, it works as expected.

**Comment by jason0x43** [comment]
The [require.js npm package](https://github.com/requirejs/requirejs-npm/tree/master/requirejs) includes a Node-compatible AMD runtime that allows it to function in Node. The Alameda package only includes the bare loader, so it won't work as a Node loader for Intern.

**Comment by httpete** [comment]
This is in the client.html browser runner.  Require.js works fine there. Alameda does not.

**Comment by dylans** [comment]
I don't think Alameda supports the AMD API for undefining a module, which is commonly needed when cleaning up after a test, or mocking/remapping a dependency ( https://github.com/requirejs/alameda#requirejs-tests-that-do-not-pass ). Though I'm not sure that's the issue here, that would be the first place I would look. Also, I assume you've included requirejs' packages for the needed loader plugins, as explained a few sections above the link on the tests that do not pass? Alameda doesn't include loader plugins for domReady, etc., so the expectation is that you'll pull those in with requirejs.

Regardless, it would help to know more about how you're trying to use this, so we can look for anything else.

And while we're on the topic, I guess I would be curious to know if Cajon ( https://github.com/requirejs/cajon ) works as well.

**Comment by jason0x43** [comment]
Sorry about that, I misread the question. What're you using for your `host-browser` string? With the alameda npm module, and with Intern's loader settings at their defaults, you would use `'../../node_modules/alameda/alameda.js'`. Doing that it works for me, at least loading a simple unit test.

**Comment by httpete** [comment]
I am just using require.js in the browser, and r.js on the server.  That works fine all round.

**Comment by csnover** [comment]
OK, sounds like there is no issue here then. Alameda works fine in browsers which is the only environment it supports.
