### ISSUE TITLE
Functional tests in node?

### ISSUE THREAD

**Issue by tmcw** [theintern/intern#438]
>  Functional tests are different from unit tests because they are executed on the local (Node.js) side, not the remote (browser) side, so they are specified separately from the list of unit test modules.

From https://theintern.github.io/intern/#runner-config

> Functional test suite(s) to run in each browser once non-functional tests are completed

From the tutorial https://github.com/theintern/intern-examples/blob/master/react-example/tests/intern.js#L59

Which one is true? Functional suites run in the browser for me.

**Comment by jason0x43** [comment]
Functional tests always run in Node.js. They work by driving a browser, inspecting its state and acting upon it, but they do not actually run in a browser.

**Comment by kitsonk** [comment]
So it is more accurate to say...

> Functional test suite(s) to ~~run in~~ *execute against* each browser once non-functional tests are completed

But we are arguing semantics.  Because *but they do not actually run in a browser* is semantics too in the sense that they partly do, as you are obviously testing some sort of functionality you have loaded into the browser but require functional inputs supplied from a controller that sits within the "server".

I guess @tmcw what sort of issue did the unclearness cause you as this may inform how to better clarify the documentation?

**Comment by sholladay** [comment]
To muddy the waters further, functional tests can have some lines of code that will run in Node, and others that will run in the browser, all from within the same file, by using [.execute()](https://theintern.github.io/leadfoot/Command.html#execute) and [.executeAsync()](https://theintern.github.io/leadfoot/Command.html#executeAsync). This can cause plenty of non-intuitive breakage of the normal rules around scoping, etc. unless you understand that it serializes that code and ships it off to a different environment. In fact, Intern makes extensive use of that (bi-directional) channel to allow you to reference actual browser DOM elements in your code that runs within Node.

It's one of those great power / great responsibility situations.

I would summarize it like this, for functional tests:
 - 100% of your code is always defined within the Node environment, at least originally.
 - At runtime, your code is _typically_ bound and executed in Node, per the usual rules there. However, some code (such as the callbacks to `.execute()` and `.executeAsyc()`) will be turned into strings, sent to the browser, and then re-evaluated and run within that environment.
 - Because of the use case for functional tests, most of your code will probably be designed to control the behavior of a browser through [Leadfoot](https://theintern.github.io/leadfoot/), which knows how to speak the [WebDriver](https://en.wikipedia.org/wiki/Selenium_(software)#Selenium_WebDriver) protocol and ships with Intern. But nothing demands that you do so, your functional tests _could_ completely ignore that web browsers even exist - it would just be an odd thing to do.

**Comment by jason0x43** [comment]
Yeah, we could use some better documentation for this. There really isn't any ambiguity about where code runs -- it's always Node unless you're calling a function that explicitly states that it runs code in the browser context (`execute`, `executeAsync`, `pollUntil`). Even those functions aren't really exceptional. Like the other Leadfoot functions, they're just instructing the browser to do something ("execute this code"). The Leadfoot user guide doesn't really explain the implications of running code in the browser, though, such as that it has access to the browser environment rather than the functional test scope.

You're right about functional tests and browser interactions. You don't *have* to talk to the browser in a functional test, but at that point Intern just started up a browser for nothing. :)

**Comment by csnover** [comment]
Is the resolution of this issue just the documentation change that Kitson suggested?

**Comment by jason0x43** [comment]
That, and maybe notes in `exec` and `execAsync` explicitly pointing out that the given code runs in the browser's context, and hence doesn't have access to the functional test context.

**Comment by csnover** [comment]
Thanks for your report! Hopefully the new documentation changes are clearer.
