### ISSUE TITLE
Cannot set basePath argument via command line

### ISSUE THREAD

**Issue by krishollenbeck** [theintern/intern#449]
From what I am reading in the DOCS it seems like I should be able to do this. https://theintern.github.io/intern/#test-runner

```
intern-runner config=tests/intern basePath=my/new/path
``` So when I try to change the basePath via command line I would expect it to try to run tests/intern from the new path (where tests/intern is actually located). But instead it continues to run from the location the command was ran from.

This question is also on StackOverflow.
http://stackoverflow.com/questions/31711594/internjs-how-to-set-base-path-on-command-line

**Comment by csnover** [comment]
The [documentation](https://theintern.github.io/intern/#test-runner) for the `config` argument states:

> The module ID of the Intern configuration file that should be used. **Relative to the current working directory.** This argument is required.

So, `basePath` *is* being set correctly in your example, it just does not apply to the `config` argument, which is defined to *always* be relative to the current working directory.

On a technical level this is because the runs this way:

1. Load the base loader
2. Load the configuration file
3. Overwrite any configuration settings from the configuration file with arguments specified on the command line
4. Configure the test system

So the configuration file is loaded before any other arguments are considered.

It would be very straightforward to change this so that the `basePath` from command-line is considered when loading the configuration file, but the documentation currently is pretty explicit that this is how `config` works at the moment, so this would be considered an enhancement.

I would like to solicit opinions from others about whether they think that the current behaviour is good or that `basePath` should be considered specially when loading the config before making any change.

**Comment by kitsonk** [comment]
My opinion is that it would be "surprising" on the command line for `basePath` to affect the path of the `config` argument.  I could understand `basePath` being applied after the config is loaded, but I would logically assume the path for config is relative to where the command is being run.

**Comment by krishollenbeck** [comment]
@kitsonk , Yes I think that is sort of where my misunderstanding came from as well. At first I was trying to do something like ````confg=my/path/tests/intern````, but then I had read this.

>The config argument is a module ID, not a file path. Providing a file path may cause confusing or unpredictable results.

So I knew that wouldn't work. But a bit further down in the documentation I read this.. 

> You can also specify any valid configuration option as an argument on the command-line.

Which lead me to believe I could use the ````basePath```` argument to set the base path via the command line. 

https://theintern.github.io/intern/#test-runner

**Comment by csnover** [comment]
I’ve removed the warning about the value of `config` since I had to introduce a workaround in Intern 3 for the fact that people kept using it as a file path anyway. :) If you are doing stuff from Grunt maybe the better enhancement is for cwd to be optionally configurable in the Grunt task?

**Comment by krishollenbeck** [comment]
I just ended up installing intern globally for now. This wasn't ideal as now we have to make sure to install intern global on our build machines. But I just add something into our build to install intern global for now. But I do think this would be a nice option to have in the future.

##### My solution here:
http://stackoverflow.com/questions/31711594/internjs-how-to-set-base-path-on-command-line/31735386#31735386

**Comment by sholladay** [comment]
To me, the currently documented behavior makes more sense.

**Comment by jason0x43** [comment]
The basePath can now be set from the command line, or via config. It is implicitly set to the location of the config file.
