### ISSUE TITLE
Failed to use stealjs as module loader

### ISSUE THREAD

**Issue by duongphuhiep** [theintern/intern#453]
I want to use [steal](http://stealjs.com/) as the module loader in [intern](https://theintern.github.io/). Is it possible? How can we do it? I tried but...

`intern.js`
```js
loaders: {
	'host-browser': 'bower_components/steal/steal.js',
	'host-node': 'steal'
}
```
Run ` intern-client config=tests/intern` gives
```
TypeError: Cannot read property 'then' of undefined
  at steal  <node_modules\steal\main.js:197:25>
  at <node_modules\intern\lib\executors\PreExecutor.js:272:5>
  at new Promise  <node_modules\intern\node_modules\dojo\Promise.ts:411:3>
  at PreExecutor._loadExecutorWithLoader  <node_modules\intern\lib\executors\PreExecutor.js:271:11>
  at loadExecutorWithLoader  <node_modules\intern\lib\executors\PreExecutor.js:345:17>
  at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
  at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
  at run  <node_modules\intern\node_modules\dojo\Promise.ts:237:7>
  at <node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
```

**Comment by jason0x43** [comment]
I haven't used steal, but the problem seems to be that steal's loader function has a large number of functions attached to it, including a `then` function. If the steal loader is used to resolve a Promise, which Intern does when loading a new loader, problems ensue. Promise implementations treat an object with a `then` property that's a function as a "thenable", and attempt to resolve it as such. The steal loader, however, is not an unresolved thenable and doesn't behave as such.

This also relates to https://github.com/stealjs/steal/issues/452.

**Comment by duongphuhiep** [comment]
Thanks for the explanation, so is it potentially a bug of inter / or we can simply say that stealjs is not compatible with intern, and we would not use it here?

**Comment by jason0x43** [comment]
Actually, after looking at steal a bit more, it doesn't appear to be compatible with Intern. While steal is able to load AMD modules, it is not an AMD loader (it provides a different API). Intern needs an AMD loader, so steal isn't going to work.

**Comment by matthewp** [comment]
> While steal is able to load AMD modules, it is not an AMD loader (it provides a different API). Intern needs an AMD loader, so steal isn't going to work.

What APIs are you referring to?  The loader plugin API is different from RequireJS, but RequireJS compatibility and AMD-compatibility are not the same thing.

**Comment by vladikoff** [comment]
> What APIs are you referring to? The loader plugin API is different from RequireJS, but RequireJS compatibility and AMD-compatibility are not the same thing.

Sorry if I missed a comment somewhere, how does RequireJS relate to this?

**Comment by matthewp** [comment]
I'm referring to this comment:

>  While steal is able to load AMD modules, it is not an AMD loader (it provides a different API).

What is the API that is different?

**Comment by csnover** [comment]
> What is the API that is different?

Presumably, `steal.import` instead of `require`.

**Comment by matthewp** [comment]
the `require([], callback)` is supported in modules but looks like it's not in a script tag, I can't remember why this is.  Is this how Intern loads stuff?  Should be a fixable bug.  Let me know if there are other issues.

**Comment by csnover** [comment]
Yeah, this happens at the place where we try to call into the new loader for the first time after injecting it. Since we aren’t inside the loader we have to call a globally exposed API. I would not be opposed to receiving a patch that looks for some other loader API hooks, I believe you would need to patch just `lib/util.getModule` and `lib/executors/PreExecutor#swapLoader`.

**Comment by jason0x43** [comment]
Sorry about that, it would have been clearer to say that steal doesn't currently return or globally provide a require-compatible loader, which is what Intern is currently looking for. After reading through the docs, I was under the impression that steal's goal was to be able to load AMD modules, not necessarily act like a require-based loader.

In any case, steal could provide a global `require`, or its default export could have a `require` function, and Intern could be patched to look for that.
