### ISSUE TITLE
Unable to run unit test cases on Selenium Grid

### ISSUE THREAD

**Issue by hjain60** [theintern/intern#470]
I am trying to run unit test cases on Selenium grid using intern. Is it even supported?

Here is my config file:
{
        environments: [
            {
                browserName: chrome,
                chromeOptions: {
                    args: [
                        'disable-restore-session-state',
                        'disable-web-security',
                        'no-sandbox'
                    ]
                }
            }
        ],

        suites: [
            'tests/unit/app/application'
        ],

        proxyPort: 9000,
        proxyUrl: 'xxxx:9000/',

        tunnel: 'NullTunnel',

        tunnelOptions: {
            host: 'xxxx:4444',
            port: '4444'
        },
    }

**Comment by jason0x43** [comment]
Try adding an empty functionalSuites array: `functionalSuites: []`. This seems to be an issue with the runner -- it hangs if functionalSuites isn't specified.

**Comment by hjain60** [comment]
I added the following :
functionalSuites: [ ]
How ever I see the following error and also the test are hung with this error:
 - Error:This webpage is not available
 - ERR_CONNECTION_REFUSED

The URL on the browser is :
http://xxx:9000/__intern/client.html?config=tests%2Funit-client-config-grid&reporters=webdriver&suites=tests%2Funit%2Fapp%2Fapplication&suites=tests%2Funit%2Fapp%2Fcommon%2FcommonUtil&suites=tests%2Funit%2Fcomponents%2Fnode-detail-general%2Fcontroller&suites=tests%2Funit%2Fcomponents%2Fnode-detail-general%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items-rules%2Fcontroller&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items-rules%2Fviews%2Fcondition&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items-rules%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items-rules%2Fviews%2Frule&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items%2Fcontroller&suites=tests%2Funit%2Fcomponents%2Fnode-detail-items%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-detail%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-layout%2Fcontroller&suites=tests%2Funit%2Fcomponents%2Fnode-layout%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-master%2Fcontroller&suites=tests%2Funit%2Fcomponents%2Fnode-master%2Fviews%2Findex&suites=tests%2Funit%2Fcomponents%2Fnode-search%2Fviews%2Findex&suites=tests%2Funit%2Fmodels%2Fnode%2Fmodel&baseUrl=%2F&sessionId=9e1d6fc6-2bd1-411f-bf3c-15fbd7a1b7b2

**Comment by jason0x43** [comment]
In tunnelOptions, don't include the port in your hostname.

**Comment by csnover** [comment]
In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions.

The [user guide](https://theintern.github.io/intern/#test-runner) describes how to use the test runner with a Selenium Grid, and even how to set up a Selenium Grid. If you are still having trouble I would recommend asking for help on Stack Overflow.

Thank you again for your interest!
