### ISSUE TITLE
Support packages option for Node.js loader

### ISSUE THREAD

**Issue by orlade** [theintern/intern#490]
_Disclaimer: I'm still new to intern, so this may be possible but I don't see it._

The Intern configuration supports `loaderOptions: {packages: [{name: 'app', location: 'path/to/some/root'}]}`. This configures the test loader to load modules with clean IDs like 'app/some/Module' rather than potentially ugly filesystem paths.

However the Node.js loader doesn't seem to support that configuration option, requiring test modules to load app modules like `require('intern/dojo/node!../../../../path/to/some/root/some/Module')`. This is a pain to type and refactor. ([Here's the problem I had on StackOverflow](https://stackoverflow.com/questions/32473471/error-importing-node-js-modules-into-intern-tests/32493240#32493240).)

Is there some way to configure the node loader to use a similar `packages` configuration to the standard AMD loader to clean up the `require()` statements in the tests?

**Comment by gitgrimbo** [comment]
I'm having the same issue.  I've checked the docs and samples and can't see an obvious way how to do this.

There are bits and pieces about [writing tests](https://github.com/theintern/intern-tutorial/issues/18) in a [CommonJS format](https://gist.github.com/jason0x43/3e3c00265c3fc573b48d), but I want to write the tests using AMD and write my Node modules using *Node-style* code.

So I'm currently using `require('intern/dojo/node!...` and relative paths in my tests to my module code (like you are) which I'm not happy with.

E.g. I've looked at the Leadfoot code and it uses relative paths:

https://github.com/theintern/leadfoot/blob/1.5.2/tests/unit/lib/util.js#L1-L5

````
define([
	'intern!object',
	'intern/chai!assert',
	'intern/dojo/node!../../../lib/util'
], function (registerSuite, assert, util) {
````

rather than something like:

````
define([
	'intern!object',
	'intern/chai!assert',
	'intern/dojo/node!leadfoot/lib/util'
], function (registerSuite, assert, util) {
````

(https://github.com/theintern/leadfoot/blob/1.5.2/lib/util.js is *Node-style* module)

**Comment by sholladay** [comment]
One alternative to this is to use project relative paths, which are much more intuitive usually.

https://www.npmjs.com/package/pkg-dir

**Comment by disterics** [comment]
+1 
I would also like not to use relative paths in my tests

**Comment by bartoszkaczorek** [comment]
+1
Refactoring paths starting like "../../../../../" is a nightmare.

**Comment by jason0x43** [comment]
This is really a Node issue rather than specifically an Intern one. The Node loader doesn't support the concept of packages in the same way as an AMD loader, and relative paths are the standard way to require modules within a project.

There's a template floating around somewhere describing one way of loading CommonJS test modules. We could potentially adapt that and build it into Intern, giving users a designated way for loading CommonJS suites. Intern could then provide a project-level Node loader to test modules.

**Comment by jason0x43** [comment]
Intern now uses the native Node loader, so loading modules with Intern works the same as for any other Node project. You can set NODE_PATH to make application code look more like a package to Node.
