### ISSUE TITLE
How do I run tests in parallel on same browser / platform?

### ISSUE THREAD

**Issue by foooocus** [theintern/intern#503]
I have functional UI tests and need to run concurrently.

**Comment by csnover** [comment]
In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions. Thank you!
