### ISSUE TITLE
new session for each request -  CSRF handling in Intern

### ISSUE THREAD

**Issue by Suyogsawant11** [theintern/intern#522]
As i have one unit test which fails due to CSRF protection.

How to handle this as first i made an get request to server to get cookies and csrf token now in next post request i have to send the csrf token which fails.

    define(function(require){
        var registerSuite = require('intern!object');
        var assert = require('intern/chai!assert');
        var request = require('intern/dojo/node!request');

    registerSuite({
    	name : 'HomePage',

    	'home page form':function(){

            var dfd = this.async(3000);

            request({ url:'http://localhost:8000/'}, dfd.callback(function(error,response){
                console.log(response);
                var data = { 
                    url:'http://localhost:8000/api/vehicles/80/variants/',
                    data : {
                        'name':'abc',
                    },
                     headers:response.headers,
                };

                request.post(data, dfd.callback(function(error,innerResponse){
                         // CSRF warning
                }));

            }))

    		;
    	},
    });

    });

i guess every request has it new session , it does not happen in one session.
Even if so how to set headers in next request?? , how should we pass the entire cookie?? so that csrf protection can be handled.

**Comment by csnover** [comment]
Thanks for your interest in Intern!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions. Thank you!
