### ISSUE TITLE
loaderOptions + AMD Generation from typescript

### ISSUE THREAD

**Issue by nimaen** [theintern/intern#532]
Hi,

I'm trying to use a Typescript to AMD + Intern stack.
I'm loading an external lodash module at some point, therefore, I need to specify some loaderOptions If I am correct.

Like this :
```json
"loaderOptions": {
  "packages": [
    {"name": "lodash", "location": "node_modules/lodash-amd"}
  ]
},
```

Fact is : it breaks the loader dependencies. When trying to load the bdd interface, it seems like the tdd it not loaded (ie. beforeEach is missing on bdd by example).

I have looked for several hours now, no clues...
I would appreciate any idea :)

**Comment by csnover** [comment]
Thanks for your interest in Intern!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions. Thank you!
