### ISSUE TITLE
Why skipping a test makes a suite to fail?

### ISSUE THREAD

**Issue by brunano21** [theintern/intern#533]
In my suite if a previous test fails, then I skip all the remaining tests. Further, if a test.name is part of excludedTest array, then I skip it. 
However, if I skip a test, my suite is marked as failed even if a fail did not occur. Why?
How can I solve that?

**Comment by brunano21** [comment]
Hi,
is this recognized as a real issue?

**Comment by csnover** [comment]
Thanks for your interest in Intern!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions. Thank you!

**Comment by brunano21** [comment]
So is it not a bug this? Everything is as expected?
