### ISSUE TITLE
Async tests are flaky, sometimes fail, sometimes pass

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/intern#539]
Out of ~1800 tests I have 3 that keep failing/passing (without code changed in the meantime) in Firefox and Internet Explorer. Excerpt from the [Travis log](https://travis-ci.org/medialize/ally.js/builds/92799294#L1616):

```
× Firefox 41 on WIN - unit tests - style/focus-source - pointer (1.065s)
CancelError: Timeout reached on Firefox 41 on WIN - unit tests - style/focus-source - pointer
```

The [test](https://github.com/medialize/ally.js/blob/master/test/unit/style.focus-source.test.js#L85-L106) is asynchronous with a set timeout of `1000ms` and a fixed delay of `200ms`. I don't understand how that can lead to a CancelError after 1 second.

Any suggestions regarding how to debug/solve this? Possibly related to #521

**Comment by csnover** [comment]
Hi, happy to see a great accessibility project like ally.js using Intern!

You will probably need to increase your test timeout beyond 1 second. This is entirely speculative, but I believe that due to overallocation/CPU steal from other VMs running on the same physical hardware, sometimes the cloud VMs have long (several hundred ms) delays running code, so the tests end up timing out. The problem is more significant on Sauce Labs than BrowserStack because they seem to significantly overallocate, but the problem exists pretty much everywhere. This was an ongoing annoyance when Intern self-tests were put on the cloud; if you look through our commit history you’ll see me progressively ramping up timeouts on some of our tests until they finally would pass reliably on cloud hosting, even though they always passed 100% of the time locally.

I’d like to figure out a better way of handling this but I am not sure what would be ideal, or if it is even possible. Because the lag is largely nondeterministic, it’s not possible to do something like benchmark. If part of the problem is that timeouts are executing on the same event loop but in an undesired order (i.e. the timeout function fires, and then the callback for the test fires next during the same cycle)—and again this is all speculative—it would be simple to add an extra guard loop for the timeout so that it won’t trigger a timeout failure until n+1 event cycles, and only does so on the second cycle if it turns out the callback was not executed during the last cycle. If you want to prototype something like that it should be pretty straightforward to modify `intern/lib/Test#restartTimeout` which is where the timeout handling occurs.

You can also manually reset the timeout from your tests now by calling `this.restartTimeout`, which is useful if you have some outside mechanism that lets you know that your async operation is still working, though this won’t help in the situation where VM lag is greater than your timeout.

**Comment by rodneyrehm** [comment]
> Hi, happy to see a great accessibility project like ally.js using Intern!

consider the compliment returned ;)

> I’d like to figure out a better way of handling this but I am not sure what would be ideal

If a test fails because of CancelTimeout simply re-run the the test with doubled timeout (after a short delay to allow the VM to breathe). Allow specifying the times to retry-while-increasing the timeout in the async-call: `this.async(timeout, {retry: 3})`, with `{retry: false}` disabling the feature. In case a retry succeeded, print a warning so the developer has a chance to increase the initial timeout. (At least that was the naive approach I intended to take with DalekJS, back when we still thought we'd go through with Skaro).

I'll try increasing the timeouts by 10x and see what happens. Thanks for the hint and thanks for all your efforts on Intern, *much* appreciated!

**Comment by rodneyrehm** [comment]
I'll take [3 successful builds](https://travis-ci.org/medialize/ally.js/builds) in a row means increasing the timeouts "fixed" it. :dancers: 

thx!
