### ISSUE TITLE
Addressing a source of false positive tests

### ISSUE THREAD

**Issue by wonnage** [theintern/intern#551]
I like being able to return a promise instead of using `this.async`, but it's easy to forget that return statement, and now your test is immediately marked as succeeded (while the actions continue on in the background, as the following tests run in the same session...)

Would be great if test success was made more explicit - maybe usage of `this.remote` ought to mark the test as async as well? I've seen other test frameworks pass a done callback into the test functions.

**Comment by csnover** [comment]
It would be possible to mark a test as async if someone tries to access `remote`, but no way to correctly handle the actual usage of the remote object, since it generates a Promise object chain rather than being a single object with an internally held stack or queue.

Maybe it would be better to flag any access of `remote`, check if the test is async after the test function runs, and if remote was access and there’s no async handling, emit a warning? That seems like it strikes the right balance between not insane to program and helpful to end-users. Let me know what you think.

With regards to the done-callback-signature, I don’t feel that is the right approach generally, but of course if you really think this would help you/your team you can write a custom test interface that has something like that too, and if that is super popular for some reason then it could be included I guess.

**Comment by wonnage** [comment]
I like the warning idea, does the approach in the patch look reasonable?

**Comment by csnover** [comment]
Yep, it’s on the right track! I sent some line comments.

**Comment by sholladay** [comment]
My second favorite test framework, [ava](https://github.com/sindresorhus/ava), has the concept of an [assertion plan](https://github.com/sindresorhus/ava#assertion-plan) that helps with this sort of thing a ton. In fact, it allows a test to be considered failed until proven otherwise.

**Comment by csnover** [comment]
Assertion count check is something that already exists in the QUnit test interface today. However I would think if someone forgets to return a promise they will just as easily forget to call a method for counting assertions too?

As an aside, the reason why there is no fully integrated assertion count now (i.e. why it is only in the QUnit interface) is because it’s not possible to count number of assertion checks if someone is using their own assertion library, so it would either be some extra separate check-pass API, or we need to expose some thing to let people “bless” their preferred assertion library, or we would need to restrict what assertion library people use when they also want to use assertion count check.

**Comment by sholladay** [comment]
Make it so a test must explicitly opt-in or opt-out of having an assertion plan (or less drastically, just a config flag to opt-in globally). Since a test must end having made exactly the number of assertions specified in the plan count, if you forget anything, the test fails with a clear message (too many or too few assertions or no plan).

Custom assertion libraries could be used by hooking them, akin to `promisify`-ing callback APIs, which is pretty painless.

**Comment by jason0x43** [comment]
Closing this for now; we can open a new issue if we want to consider assertion plans.
