### ISSUE TITLE
Prevent stale configuration

### ISSUE THREAD

**Issue by dylans** [theintern/intern#563]
I think it would be very useful if there was a mechanism to keep a user's Intern configuration current. Things that typically get stale are:
- Selenium version
- Browser versions (for cloud/grid testing)
- Operating system versions (for cloud/grid testing)

Knowing which version of Selenium is stable and works reliably with which browser and driver versions is always a fun exercise as well.

Some possible ways to improve things:
- Store metadata somewhere that people can just copy/paste when their configuration stops working
- Making sure we keep our example configuration updated regularly
- Separate repo that just provides a few sample configurations that is updated regularly
- Setup an API with relevant configuration settings, that the configuration can read

**Comment by sholladay** [comment]
Figuring out the Selenium compatibility matrix has definitely been a challenge, especially when there is a new release of either a browser or Selenium. It is surprisingly hard to find good data about that. And testing it on your own is frustrating because you typically get a confusing error, rather than a clean "this isn't compatible" message.

For keeping cloud browser/OS versions up-to-date, I would like to be able to use version math in the configuration, "latest" and "latest-1", etc. It would be great if that were [available upstream](https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-25), but a web service could be a stopgap. It would need to normalize the syntax across the various cloud providers. I currently leave commented out environment objects for switching between SauceLabs and BrowserStack ... yuck.

**Comment by jason0x43** [comment]
Using the default version for the OS and/or browser (by not specifying a version) with cloud testing services will typically use the latest stable version. For local testing, the proper driver to use depends on what browser the user has. https://github.com/theintern/digdug/issues/71 will help keep that up to date.
