### ISSUE TITLE
Path normalization breaks URL

### ISSUE THREAD

**Issue by olemis** [theintern/intern#584]
Path normalization code in lib/util.js transforms `http://domain.tld/path/to/file` into `http:/domain.tld/path/to/file` , which breaks all subsequent resolution of relative paths, specially when invoking `switchLoader()` .

**Comment by jason0x43** [comment]
The path normalization code is only intended to run on paths, not complete URLs. What is the use case where this issue appearing?

**Comment by olemis** [comment]
I'm trying to replace dojo loader with require.js . Then configuring the later's basUrl (via `loaderOptions`) to be an absolute URL , which [seems to be supported](http://requirejs.org/docs/api.html#config-paths) . Nonetheless , the issue comes to light since intern pre-executor always normalizes paths at load time, thus changing URL scheme prefix .

**Comment by jason0x43** [comment]
The problem is that the `isAbsoluteUrl` check in PreExecutor in a Node environment assumes that whatever is passed to it is a file path, not a URL. Updating it to consider URLs appears to fix the problem, but that only works with `requirejs`, which will try loading from both a URL and using Node's require (Intern's Dojo loader will only use Node's loader in a Node environment, which doesn't support URLs).

**Comment by olemis** [comment]
I see this issue from a different perspective .

Firstly , the check for URLs is backwards compatible . IOW, after applying the patch, if a path is supplied in configuration entries , as usual , then the system behaves exactly the same as it did before applying the patch .

Besides , if Intern offers the possibility of switching to a custom AMD loader, then there is no reason for polluting the configuration values that will be supplied in to that loader ( as I mentioned above normalization function breaks URL syntax ) . In that case it is obvious that Intern's Dojo loader is not meant to be used , so the fact that it (Intern's Dojo loader) does not support URL syntax is not applicable as a valid constraint or supporting argument anymore .

Thirdly , if URL syntax should be used under certain conditions (which is true in my particular case) , and a path should be supplied in when running tests on node environment , then conditional code may be executed prior to declaring config option values .

Finally , all the following loaders seem to support URL syntax : requirejs , cajon , system.js , curl.js , melchior.js , browserify , steal.js , qoopido.demand ... and maybe others , I just stopped after these . Something else I noticed is that they also support the scheme-relative URL syntax e.g. `//cdn.jsdelivr.net/jquery/2.1.4/jquery.min` . In that case Intern's path normalization would also remove the two leading slash chars , thus breaking config semantics (again) not meant to be handled by Intern's Dojo loader .

**Comment by jason0x43** [comment]
The issue isn't with `normalizePath`, because as it's name suggestions, it's meant to normalize paths. It is not intended to be applied to URLs. If it is, something else is wrong. In this case, the problem is that sometimes when `normalizePath` is used to create the loader's base URL, it's being applied to URLs.

If `loaderOptions.baseUrl` is a URL in a Node environment, `PreExecutor` will try to normalize it. That's not really a bug, though, because using a full URL as the baseUrl in a Node environment is an invalid use case. (Although all of the loaders, including Intern's Dojo loader, support loading modules from URLs, most/none of them can do so when running in a Node context.)

If `loaderOptions.baseUrl` is a schema'd URL in a browser, `PreExecutor` doesn't try to normalize it, so that's fine. However, `PreExecutor` _will_ try to normalize a schema-less `loaderOptions.baseUrl`, and that's a bug.

So, there _is_ a bug, and although changing how `normalizePath` works is one way to deal with it, I'd prefer to fix the root issue (improper use of `normalizePath`).
