### ISSUE TITLE
Feature Request: use SystemJS as the default loader (or at least support it)

### ISSUE THREAD

**Issue by andyearnshaw** [theintern/intern#615]
SystemJS can load modules of any format, so es6 and commonjs modules could be loaded in the browser alongside AMD modules.  This would provide out-of-the-box testing for a variety of different code styles and eliminate the requirement for compilation steps before intern is launched.

Intern is great, but setting it up to test non-AMD code in the browser is a real pain point.

**Comment by andyearnshaw** [comment]
As mentioned in #626, https://github.com/andyearnshaw/intern-systemjs-loader provides an interim solution for using SystemJS, which allows running tests without a precompile step if there's a SystemJS plugin for doing it.

**Comment by michaeljota** [comment]
Is there any plans to support Webpack somehow? SystemJS it's not hard to configure, but Webpack it's also very popular.

**Comment by dylans** [comment]
@michaeljota with Intern 4 (which is well underway in development), yes. I'm currently drafting a blog about the decisions around Intern 4, but here's the gist from the blog post which is not yet published (it's still a draft, but hopefully it's clear enough):

When Intern began, AMD was the only practical way to effectively load modules both in a browser and within Node.js without a compile step. Since then, ES Modules (ESM) have become the preferred standard way of authoring modules, and various tools such as webpack have changed the way people think about module loading and bundling.

Given the diverse perspectives on how to load modules, we are removing module loading from Intern's purview. While this may seem like we're offloading work to the user, it will actually simplify test writing in most cases. Rather than requiring projects to adapt to Intern’s AMD environment, Intern 4 will adapt to the user’s environment.

The result is that Intern and its packages will be loaded like any other module, and Intern can be built/optimized for a target environment and/or loader. We believe this will make it simpler for users and developers to understand and use.

As part of the move away from assuming the presence of a module loader, Intern will no longer dynamically load modules (meaning the AMD loader plugins go away). Instead, when the user loads a particular test executor (e.g. Node.js), all relevant code for that environment is loaded, e.g. all usable reporters, interfaces, and utility functions.


I don't yet know when Intern 4 will be ready, but we're pretty far along.

**Comment by jason0x43** [comment]
Closing this since SystemJS is a supported loader for Intern 4
