### ISSUE TITLE
intern started to fail when running tests after browser_modules has been introduced

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#628]
### Overview

Intern started to fail after update from 3.0.6 to 3.1.0 because it cannot find "has.js" file under "node_modules/intern/browser_modules/dojo/has.js". File structure shows that "dojo" is kind of link but it doesn't work under Windows (I'm guessing it works ok under Linux). Tests run fine with intern 3.0.6.
### Console output

``` console
> intern-client -config=test/support/config/intern.js
D:\repositories\bugs-intern\bug-intern-browser-modules\node_modules\intern\node_modules\dojo\loader.js:490
                     throw new Error('Failed to load module ' + module.mid + ' 
                           ^
Error: Failed to load module intern/browser_modules/dojo/has from D:/repositories/bugs-intern/bug-intern-browser-modules/node_modules/intern/browser_modules/dojo/has.js (parent: intern/browser_modules/dojo/has!2!*)
    at D:\repositories\bugs-intern\bug-intern-browser-modules\node_modules\intern\node_modules\dojo\loader.js:490:27
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)
npm ERR! Test failed.  See above for more details.
Result: 1
```
### Environment details

Intern: 3.1.0
node.js: v0.12.2
OS: Windows 7
### Steps to reproduce
1. Clone bug repository:  
   `git clone https://github.com/bugs-intern/bug-intern-browser-modules.git`
2. Install dependencies:  
   `cd bug-intern-browser-modules`  
   `npm install`
3. Run tests:  
   `npm test`

**Comment by jason0x43** [comment]
I don't have a Windows 7 system handy, but the test case appears to work properly (following "Steps to reproduce") on Windows 10 + Intern 3.1.0 + node 6.0.0 and MacOS 10.11 + Intern 3.1.0 + node v0.12.0. It's possible there's a specific issue with Windows 7 or Node v0.12.2, but it'll be a bit before I have a test system setup.

The introduction of `browser_modules` didn't really change the structure of the intern install; previously, some or all of the packages symlinked under `browser_modules` were symlinked under `node_modules` (depending on whether Intern got it's own copies of packages during `npm install`).

**Comment by jason0x43** [comment]
Ok, I was finally able to reproduce this:

1. Install a project with Intern as a dependency. npm will flatten the dependencies, ending up with `node_modules/dojo`, and `node_modules/intern/browser_modules/dojo` will symlink to that.
2. Update the project to use its own dojo, or just `npm install dojo@1.11.0`. This will cause Intern's dojo to move from `node_modules/dojo` to `node_modules/intern/node_modules/dojo`. npm will not rerun Intern's `fixdeps.js` script, so the link in `browser_modules` will be out of sync.

Currently the simplest way to update the links is to remove and reinstall intern.

This wasn't an issue before because Intern always looked into `intern/node_modules` for its dojo, and npm moving dojo from `node_modules` into `node_modules/intern/node_modules` would simply overwrite the symlink, so nothing would change from intern's point of view.

This would be easy enough to fix automatically with the runner or client scripts; they could always check and update symlinks if necessary during intern's startup process. However, the browser client can't do that. Possibly the initial fixdeps script could copy the necessary packages into `browser_modules` rather than linking them. Another option would be to switch back to `node_modules`, but that can lead to extraneous warnings from npm, and breakage of things like shrinkwrap.

**Comment by SaikiranHegde** [comment]
I was also facing the same problem in windows but when I changed the symbolic links of folders dojo, chai and diff to normal folder , my test started running..
![image](https://cloud.githubusercontent.com/assets/7345152/16189363/a9ae8282-36f7-11e6-8ddd-a0585d36cc58.png)

**Comment by jason0x43** [comment]
That will happen if the symlinks become invalid.

I'm leaning towards just copying the packages into `browser_modules` rather than symlinking, and replacing the copies if the versions get updated.

**Comment by skrishnas** [comment]
Here's how I solved it:

Navigate to this page and search for "allowLinking":
https://tomcat.apache.org/tomcat-7.0-doc/config/context.html

In short what needs to be done is to enable linking by setting the aforementioned parameter in the server.xml file. Tomcat then is able to follow symlinks.
Hope this helps.

**Comment by jason0x43** [comment]
Interesting. I haven't seen a lot of use of Tomcat as an Intern server, but that seems like another reason to consider copying the relevant packages instead of linking them.

**Comment by jason0x43** [comment]
The latest release of Intern copies the relevant packages into browser_modules rather than linking them. Give that a try.

**Comment by bartoszkaczorek** [comment]
I have tried with intern 3.3.2 and can confirm that issue does not occur anymore. Thanks!
