### ISSUE TITLE
Consider removing CLA

### ISSUE THREAD

**Issue by sushantdhiman** [theintern/intern#638]
This is the biggest barrier for new contribution into the project. I would love to contribute but I don't want to sign CLA

**Comment by kitsonk** [comment]
Why don't you want to sign a CLA?

While there is some debate on if a CLA is needed or not, most major projects require them (e.g. Angular 2, V8, Chromium, jQuery, TypeScript (and all Microsoft Open Source Projects), Dojo, etc...).

**Comment by sushantdhiman** [comment]
> Why don't you want to sign a CLA?

Mostly because I don't want to share all this personal info just to contribute to a project.

Yes there are some projects that still require CLAs but most of open source projects like (NodeJS, ROR, Bootstrap ) don't require CLA

**Comment by kitsonk** [comment]
> Mostly because I don't want to share all this personal info just to contribute to a project.

First Name, Last Name and an e-mail address are [too much personal information](https://contribute.jquery.org/CLA/)?  That is what you would essentially be providing with a Pull Request anyways.

It is potentially a fair point that the Dojo Foundation one asks a bit too much information.  Since the foundations have merged though, either a jQuery or Dojo Foundation CLA would work for this project.  I am pretty sure we are going to abandon the Dojo Foundation one, once we merge the databases and rebrand the jQuery one to the combined Foundation.

>  most of open source projects

That is debatable, you listed 3, I listed 6 Open Source Projects.

**Comment by sushantdhiman** [comment]
> First Name, Last Name and an e-mail address are too much personal information? That is what you would essentially be providing with a Pull Request anyways.

Sorry that was my mistake, I thought everything in CLA form was required. I have no regrets in sharing what is already public.

> That is debatable, you listed 3, I listed 6 Open Source Projects.

:beers:

**Comment by kitsonk** [comment]
> Sorry that was my mistake, I thought everything in CLA form was required. I have no regrets in sharing what is already public.

We need to update our documentation so that we are pointing to the jQuery form.  I do think the Dojo Foundation form does require additional personal information that is unnecessary.

**Comment by sushantdhiman** [comment]
You mean https://contribute.jquery.org/CLA/

This can be my first PR :)
