### ISSUE TITLE
Add qtwebkit support

### ISSUE THREAD

**Issue by Acanthostega** [theintern/intern#673]
I would like to use intern with an embedded qtwebkit browser. There is an existing webdriver that should work with qtwebkit called qtwebdriver  (https://github.com/cisco-open-source/qtwebdriver), but I don't know how to integrate it with intern through selenium.

What I would like is to be able to specify my own browser into the configuration file of intern to be able to communicate with the webdriver through selenium (or directly with the webdriver). Is there something that can help me to integrate a new browser, webdriver into intern? If I can be redirected to a part of the code doing that, it will be really helpful. If you are interested in adding qtwebkit support into intern, I would be happy to contribute.

Thanks!

**Comment by dylans** [comment]
Hi @Acanthostega , thanks, this sounds like a good addition to Intern!

A few things you'll want to look into:

* EnvironmentType is driven via configuration in https://github.com/theintern/intern/blob/master/lib/EnvironmentType.js
* The conduit to open tests within a WebDrive implementation occurs in https://github.com/theintern/intern/blob/master/lib/executors/Runner.js which calls 
* Leadfoot capabilities ( https://github.com/theintern/leadfoot/blob/master/Server.js ). This is our collection of feature tests to run and verify in a functional testing environment before we run functional tests, so that we do not break against known defects of a particular driver implementation.
* SeleniumTunnel, https://github.com/theintern/digdug/blob/master/SeleniumTunnel.js , which allows an end user to run a command to install the requested WebDriver instances for local testing

@jason0x43 may have a few more suggestions. Let us know if you get stuck or if you have questions!

Also make sure you read through the [contributing guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) if you haven't already. One thing to note is that the Dojo Foundation has merged with the jQuery foundation, so you may use https://contribute.jquery.org/CLA/ for the CLA if you have not done so already.

**Comment by jason0x43** [comment]
Closing this since Intern can, using the "null" tunnel, communicate with arbitrary webdrivers. We can reopen this if there's something QtWebkit-specific Intern needs.
