### ISSUE TITLE
ESM - Remove loader dependency from Intern

### ISSUE THREAD

**Issue by morrinene** [theintern/intern#697]
- Testing engine framework hierarchy
- Determine what stays and what gets abstracted out
- Separate suites, tests, import object, import TDD, import BDD
- Work off of TS conversion branch

**Comment by devpaul** [comment]
Right now, from an 1000ft view, I'm looking at keeping the executors, interfaces, and reporters in the intern-core package. This should essentially give enough functionality to run tests programmatically and cut as much other stuff as possible. This includes the command-line utilities, grunt task, and likely things that do configuration parsing.

I'm also looking at separating out the current `intern/main` module into an `ExecutionContext` module that is accessible to tests, suites, and reporters via the `suite.parent` chain. The singleton nature of the `intern/main` module was fine when the executors were driven by a binary, but to allow for programmatic use of the executors we'll want to allow for separate invocations of a context. Once decoupled and no longer a singleton, we could feasibly allow for client and runner tests to run simultaneously (or potentially test against multiple versions of node concurrently via docker or perhaps using the cloud with a DockerExecutor or SSHExecutor).

The last thing I have to fit into this approach is the browser tests that run though the Intern server (proxy), and for that matter how and where the server fits into the core. On one hand, I feel like this is a tool that is outside the fundamentals of intern-core, but on the other it's a requirement for the browser test feature. It would probably be more tidy as a separate package providing intern server support, but I expect moving it to a separate package would be a disservice to our users as it would be a dependency for a large number of use cases and in turn add complexity.

Essentially these changes will allow us to instantiate an `ExecutionContext` create an `Executor` and pass the `ExecutionContext`, and allow suites to be registered to the executor. The last piece that I'm considering is registering the suites/tests provided to the interfaces in a global/singleton factory. Executors would then be able to instantiate the suite of tests from the factory. This should allow us to keep the same pattern for registering suites without limiting us to one executor. We'd still be limited to only one collection of suites. If that's problematic we could solve it by providing a test interface class that could be instantiated and used to collect tests. Unless this proves to be useful somehow for browser tests, I think it's fine if we just have one list of suites and tests and filter out ones we don't want added to a specific execution context.

With these changes we should be able to use intern programmatically

```js
import Client from 'intern/executors/Client';
import Runner from 'intern/executors/Runner';
import registerSuite from 'intern/interfaces/object';
import suiteManager from 'intern/suiteManager'
import ConsoleReporter from 'intern/reporters/Console';
import RunnerReporter from 'intern/reporters/Runner';
import assert from 'chai/assert'

const clientExecutor = new Client();
clientExecutor.executionContext.addReporter(new ConsoleReporter());

const runnerExecutor = new Runner();
runnerExecutor.executionContext.addReporter(new RunnerReporter());

registerSuite({
    name: 'unit'
    test() {
        assert.isTrue(true);
    }
});

suiteManager.generate(... clientExecutor.suites, ... runnerExecutor.suites);

Promise.all([clientExecutor.start(), runnerExecutor.start()])
```

**Comment by devpaul** [comment]
It's probably worth noting that this ticket stemmed from #685

**Comment by devpaul** [comment]
I've pushed some work to the programmatic-intern branch. There's a lot of things in the works.

We want to complete the following:

1. Add functionality to the `Proxy` to serve a `client.html` for browser tests
1. Update `client.html` to act as a template and serve it w/ a global `intern` for the browser and an injected preamble
1. Create a global `intern` script. The global `intern` injected into `client.html` for browser tests should function like Electron and provide an RPC interface for communicating between browser and node. The global `intern` will need to be compiled separate from the rest of Intern. This will require a "global" module format in tsconfig, and the rest of Intern will use UMD.
1. Create preambles for dojo 1, dojo 2, Webpack, and SystemJS (optional, but we should do this)
1. Write tests for running in tests in node, webdriver, and the browser. Test supported preambles as well.
1. Consider implementing various executors in line with the supported engines, Node (Client), WebDriver (Runner), and Browser (Currently Client, when started via CLI it also runs Proxy).
1. Update current tests
1. Fix builds, build scripts, and configurations. Remove unneeded dependencies from package.json.

So far I've succeeded in two things. Making this plan, and making an utter mess of everything. The `ts-conversion` is still in progress as of this writing. I am sure changes will need to be merged in.

**Comment by devpaul** [comment]
Spoke w/ @bryanforbes about serving up a global `intern`. We're considering using webpack to compile out a global w/o a loader.

**Comment by jason0x43** [comment]
Some notes (to accompany all the commits that now reference this issue)...

The overarching goal here is to separate the loader from Intern, such that Intern can be loaded and used like any standard JS module, with or without a loader. It should run in a Node environment, and a browser, and be able to drive tests via webdriver, and the usage model should be reasonably consistent in all of these. The Test structure should be portable between these environments (i.e., you shouldn't have to write Intern tests differently to run in a browser vs Node). To that end, the basic architecture (which is still being refined) looks like this:

* Executor (actually its subclasses) drives the testing process.
  * Reporters, Suites, and Tests can access the executor to get at global context.
  * Executors are event emitters, and serve as the main event hub for the testing process (i.e., no more ReporterManager). Reporters are just listeners for executor events.
  * Executors are environment-specific. For example, the Node executor only works in Node. The Browser executor only works in the browser.
  * Only one executor should be instantiated, and it will be assigned to an `intern` global. This allows suites to be loaded independently from Intern (once the intern global has been set).
* For the browser, a single `browser.js` script is built that contains all the browser-compatible parts of Intern. Loading it will automatically instantiate a Browser executor and assign it to the `intern` global.
* The built-in `client.html` test page will load code that processes query args and loads unit test suites via script injection. It will also provide a means for loading user-specified preamble scripts that could, for example, setup and configure a loader.
* Known types of things like reporters and Dig Dug tunnels can be specified in config structures using strings (which the executor will map to constructors). For custom reporters, constructor functions can also be provided.
* Reporters no longer have a special status; they're just event listeners. The built-in reporters all inherit from a base Reporter class, and use a method decorator to register their event handlers.
* Everything is as explicitly typed as possible.

Things that currently work (to some extent):

* The Node and Browser executors
* The WebDriver executor (for functional tests)
* The Simple (Node console), Console (browser console), and Pretty reporters
* The object interface

Some things that are still under development (this is not exhaustive):

* `client.html` and its support script.
* Instrumentation in the browser (when running webdriver tests). The existing model of instrumenting code as it's loaded through Intern's proxy will _probably_ continue to be the method of choice.
* Path resolution (tests can't depend on `require.toUrl` anymore)

**Comment by jason0x43** [comment]
Status update:

All three environments (node, browser, webdriver) are now functional at a basic level. The 'object' interface works, as do the Html, Simple/Console, Runner, and Pretty reporters.

Other changes/improvements:

* Path references are now standardized around `basePath` / `process.cwd()`. There are likely cases where this isn't working yet, but that's the goal.
* `client.html` is now `remote.html` (and all associated class names are based on "remote" rather than "client"). It loads `remote.js`, which is where all the fun happens.
* Intern now has the concept of loader scripts for the browser. These basically let the user setup whatever loader they want and use it to load test scripts and app code. Intern includes 'dojo' and 'script' loader scripts.
* Intern now includes a simple logging facility. The base executor has a `log` method for convenience, but the basic concept is just to emit 'log' events that a reporter can pick up. This can be particularly useful for run tracing in a remote browser.
* Chai is now loaded by the base executor and exposed via a `getAssertions` method. This removes the need for user tests to explicitly load chai.

**Comment by jason0x43** [comment]
Status update:

I updated the dojo and jQuery intern-example projects to use the prelim Intern 4. That worked out relatively well, although it uncovered a couple of rough spots that still need some work.

* The commits above from intern-examples have notes on what changes were required in each project.
* For projects that don't inherently need a loader, like the jQuery one, there should be a way to load app scripts without needing a custom loader script. Intern already has browser/loaders/script, but that just loads things in the suites list, and it doesn't pay attention to order.
* I've only tried out the WebDriver runner, not the browser client.

**Comment by jason0x43** [comment]
I updated the grunt task to load Intern as a library rather than starting it as a subprocess. This led to a number of simplifications in the grunt task, and also removes the limitation regarding which properties can be passed in from grunt.

I also ported over the grunt example in intern-examples to use the new task. This involved the standard modifications to the tests, as well as a minor change to the app module being tested. The app module assumed it would be creating a global value; however, this didn't work in node once the dojo loader was not longer in use, so the module was updated to make an explicit global assignment.

**Comment by jason0x43** [comment]
I started on an angular2/systemjs example. The repetition between the webdriver run script and the local browser index.html is annoying, so I'm working on sharing a bit more of that. I considered focusing on a user-constructed index.html for both local browser and webdriver testing, but that seems like it would be limiting in the long run (it would be harder to have intern divide up suites between browser sessions for parallelization, or have it run tests in more isolated environments). My current thought is to have a configurable runner page that the webdriver executor will use (as it currently does) and that the user can use as a browser client. Much as intern's browser client does now, the client will let the user provide a config.

**Comment by jason0x43** [comment]
After considering some other options, I think the current direction I'd been going for WebDriver + browser loading, which is is to use a standardized test harness/page that calls a runner script (potentially user-provided) to actually load the unit test suites and start intern, is probably the way to go. This minimizes the amount of code a user has to write while still allowing them to have full control over loader configuration (assuming there's a loader) and the test loading process.

**Comment by jason0x43** [comment]
The angular 2 example mentioned above shows what this looks like. For that one, I have a simple Node  script to kick off webdriver tests, along with a runner script to load SystemJS and the app dependencies, and the tests themselves. The example also includes a sample custom index.html script that uses the Browser executor. Out of laziness, it just loads the same runner script that's used for WebDrriver tests.

**Comment by jason0x43** [comment]
I made a number of updates to Intern's default usage model make it easier to get up and running. I also updated the angular2 example to work with this.

Intern now has two built-in runner scripts: one for node + webdriver, and one for the browser. Both of these will make use of an `intern.json` config file if available, and will check a default location if the user doesn't provide one (the config isn't necessary, but it'll find it if one's there). Options can be overridden from the command line or via query params. The goal is that you can create a very simple `intern.json` file and just run `node_modules/.bin/intern` or go to `http://localhost:8080/node_modules/intern/` and have things happen.

I also changed how loader scripts work -- they register an async callback now that's called at the start of the `run` process rather than calling the `run` method themselves. This allows Intern to pass information to the loader, such a potentially modified version of the config.

**Comment by jason0x43** [comment]
I moved all the executors back into `src/lib/executors`; the idea now is that the built-in runners will be used by default. Loading and using executors directly in scripts should still be easy, but there's a bit less of a focus on that (e.g., the Node and WebDriver executors had been directly in `src/`  as a way to make them easier to get to).

I also worked on making the argument processing code more flexible, which will allow for simpler config files and easier to work with command line and query args. For example, current intern requires `environments` to be specified as an array of objects. The new config processing code will handle `environments=chrome` from the command line, or `"environments": "chrome"` in the config file, normalizing both to `environments: [ { browserName: 'chrome' } ]`.

Another feature of the new external config format (used by config files and arguments) is that it must be JSON serializable. This means that a config can be easily loaded or constructed in something like a grunt task, and then passed directly to an executor. All properties can be passed via the command line or as query args, making it easy to override any config property.

**Comment by jason0x43** [comment]
Updates in the last few days:

- The event handling system has been fine tuned a bit. Everything that emits an event now pays attention to the return value of `emit`, so that the entire testing process will wait for async actions to complete. The testing process will also fail if a listener throws an error or rejects. Basically, executor events are now hooks into the execution process.
- The intern config now supports a `preload` property that specifies a script or list of scripts to load before suites are loaded. This is a place to register before/after callbacks (e.g., to start and stop and external server), and also a good place to load global scripts before tests if you're using one of the built-in loader scripts.
- Errors are caught in a few places they were being missed.
- A couple of user-friendly errors are now reported. For example, the Browser executor throws a useful error when it sees a glob in the suites list (because it can't process globs).
- Suite/fatal errors aren't double-reported anymore
- Executors now provide an `environmentType` property that indicates the general environment things are currently executing in (node vs browser vs webdriver).

**Comment by jason0x43** [comment]
Woo, there's a working Electron example. Implementing it exposed issues in Intern, Leadfoot, and Dig Dug, although nothing significantly broken in the architecture, so that's something. :) The config normalization process is a bit more consistent now, as are the Tunnel implementations in Dig Dug (less property repetition).

**Comment by jason0x43** [comment]
Just cleaning things up. I'm cleaning up Dig Dug and Leadfoot and creating prerelease packages, then I'll update the intern-4-pre branch and push it out here.

**Comment by morrinene** [comment]
Will create additional issues during review period as needed.
