### ISSUE TITLE
TypeDoc output cleanup

### ISSUE THREAD

**Issue by morrinene** [theintern/intern#727]
Output format is not as well structured as we'd like it.  Needs some design work/cleanup.  Get templates to get the output looking cleaner.

**Comment by jason0x43** [comment]
TypeDoc runs on Intern, Leadfoot, and Dig Dug. Unfortunately, the generated output isn't super well organizaed. Ideally we'd have something that looks structurally similar to Leadfoot's and Dig Dug's API docs now (not necessarily with the same styles; the bootstrap-like aesthetic of the default TypeDoc docs is probably fine), with top level modules in a side bar, and without a lot of noise in the property and function lists.

A stretch goal would be to improve TypeDoc's ability to handle arbitrary markdown files (besides README) so that we could just use TypeDoc to generate the entire docset for a given tool (expository docs as well as API docs).

**Comment by devpaul** [comment]
I have made some progress on running typedoc and solving some of its issues in [grunt-dojo2-extras](https://github.com/dojo/grunt-dojo2-extras) with grunt and [programmatic](https://github.com/dojo/grunt-dojo2-extras/blob/master/src/commands/typedoc.ts) implementations available. Hopefully it'll be helpful. If we could leverage a single code base hopefully we can avoid needing to replicate work.

**Comment by jason0x43** [comment]
We're doing on-the-fly custom rendering from TypeDoc JSON for the Intern API docs (rather than using TypeDoc's renderer), so this is now moot.
