### ISSUE TITLE
moveMouseTo() is failing when running the tests using geckodriver

### ISSUE THREAD

**Issue by eusebiuplosnita** [theintern/intern#745]
Hi!
So I'm running some tests against firefox using geckodriver and when I'm calling moveMouseTo() I'm getting the following Exception:

> Executing: [mousemove: 7 false])
> WARN - Exception thrown
> org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
>Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
>System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
>Driver info: driver.version: RemoteWebDriver

I've found a similar question about hovering on an element and I managed to make moveMouseTo() work with geckodriver by executing the code from moveMouseTo function like we had the mouse events broken, so I just commented that 'if' related to brokenMouseEvents

`//if (this.capabilities.brokenMouseEvents) {

   if(element){
          .................
    } else{
          ................
   }
//}`
But doing this breaks the scrolling, since moveMouseTo() can be used also to scroll for an element and also we cannot use it since the moveMouseTo() function is defined in node modules, and it will fail when we try to run the tests in Jenkins since Jenkins is running npm install every time it starts a new build. Another idea, I think, can be building a wrapper function to treat the case when we're running against Firefox, and in that case we should execute another code, and for the other browsers we can call moveMouseTo(), but in this case I'm not sure how to fix the scrolling issues for firefox.
Does anyone have any idea about how can I fix this?
Thanks!

**Comment by ajc24** [comment]
This has been here a while so I'm not sure where you still stand on this issue but I've had some issues with `moveMouseTo()` with Firefox myself lately and will update my experiences here in case it does help someone out.

I initially posted about a hover event not working out for me on **Stack Overflow** as `moveMouseTo()` simply wasn't recognised when I was running my UI automation tests locally against Firefox. I since took that question down - simply because my suggested solution didn't work correctly after all, so I tried another, updated my response and found that wasn't reliable either. So rather than give anyone false information, I simply removed the question altogether.

Right back to the topic - so what I was seeing was the same error you have highlighted here:

```
org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
```

I'm also using the following version of Firefox:
- Version 58.0.1 64 Bit

I was running my tests with `fixSessionCapabilities` set to `false` and this, initially, was causing my problems with Firefox. What I did, then, was set that to `true` instead and, while this resolved the problem, I didn't want this set to `true` all of the time. I wanted to try and set an individual value in my configuration instead. I felt there had to be a better solution out there. Surely **one** of the settings that were in my `capabilities` list had to be the one I was looking for?

So firstly, I tried setting `brokenMouseEvents` and `brokenHtmlMouseMove` to `true` in my JSON configuration for Intern 4. However these didn't resolve my problem. In fact, these didn't affect things in a positive way at all. I found these only worked intermittently or not at all (right now I can't remember which one worked intermittently and which one didn't work at all).

So what I'm doing instead - **and this works 100% of the time for me** - was setting my mouse movements to work correctly in Firefox this way:

```
this.remote.session.capabilities.brokenMouseEvents = true;
```

This has **never** failed since I set my tests up to set the `brokenMouseEvents` parameter in this way. Never.

You also mentioned about using `moveMouseTo()` to scroll to an element. Truthfully I had not considered using that method at all for that purpose (just sheer inexperience on my end - didn't realise that I could use it for that). I am scrolling my window by using a simple piece of JavaScript in the `execute` method as follows:

```
this.remote
  .execute('window.scrollTo(xPos, yPos);');
```

This may not be the ideal solution for everyone but it's working for me. I'm also using Intern 4 with tests that run on Sauce Labs and this method of scrolling is working on all devices - browsers, tablets, mobile phones etc.

Anyway, I'm throwing it out there as an option.

**Comment by iulianvechiu** [comment]
Any more news on this? Still occurs, nobody seems to care :D

**Comment by jason0x43** [comment]
We care, there just hasn't been a lot of time lately to look into this. :)

@ajc24's solution of manually setting `this.remote.session.capabilities.brokenMouseEvents = true;` is the way to go for now. That flag _should_ be automatically set by Leadfoot (Intern's WebDriver library) automatically for Firefox 49+, unless feature tests have been disabled by setting `fixSessionCapabilities` to false.

**Comment by jason0x43** [comment]
Closing this as fixed in https://github.com/theintern/leadfoot/commit/f1ede6941a79a42669b5ad0511c7b7b2c0d783da
