### ISSUE TITLE
Bug: Node inspector crash on Windows

### ISSUE THREAD

**Issue by g3r4n** [theintern/intern#938]
## Expected behavior
Intern test suits can be debug with node.js

## Current behavior
Node.js crash when attaching chrome dev tools

## Possible solution
None

## Steps to reproduce (for bugs)
1. run the command ``` node --inspect-brk node_modules/.bin/intern ```
2. open the chrome dev tools (chrome://inspect)
3. try to connect to the node instance
4. watch the console : it crashed

Commad line tool output : 
```
Debugger listening on ws://127.0.0.1:9229/b7476804-afc5-4bae-a52b-4e20815b09f8
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
XXXXXXXXXXXXXXXXXXXXXX\node_modules\.bin\intern:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Waiting for the debugger to disconnect...
```

## Environment
Intern version: 4.2.2
Node version: 8.11.1
NPM version: 6.2.0
Browser version: chrome 67

## Additional information
Windows 10

**Comment by jason0x43** [comment]
The issue is that `node_modules/.bin/intern` is a shell script, not JavaScript. This is how npm works on Windows with all packages, not just Intern. Unlike linux and Mac, the scripts in `node_modules/.bin` on Windows are shell scripts or CMD scripts that load package JavaScript modules rather than symlinks to JavaScript scripts. These shell scripts can't be loaded directly by node.

Instead, use `node --inspect-brk node_modules/intern/bin/intern.js`.
