### ISSUE TITLE
Doc sample broken: Writing tests in an HTML page

### ISSUE THREAD

**Issue by schontz** [theintern/intern#988]
The sample code in the docs page [Writing tests in an HTML page](https://theintern.io/docs.html#Intern/4/docs/docs%2Fhow_to.md/run-intern-in-my-own-test-page-in-a-browser) produces an error.

## Expected behavior
The sample should run

## Current behavior
There is an error loading `/loaders/default.js`, as it is expected to be locally available.

## Steps to reproduce (for bugs)
1. Save the sample as an HTML file
2. Replace the empty tests with some simple assertions
3. Load the page in a browser, served over localhost.

## Environment

Intern version: `intern@next`
Browser version: Chrome 74

**Comment by jason0x43** [comment]
There are a couple of issues here. `intern@next` isn't a thing, so that's a documentation problem.

Even after switching to `intern@latest`, though, there are still a couple of issues with the code in the docs. The default loader loads suites via script injection at the bottom of the body, which doesn't work when there isn't yet a body. Also, `internPath` is being resolved to a simple path, which doesn't work when Intern is being loaded from a remote system (like unpkg).

**Comment by jason0x43** [comment]
Resolved in cab38e6 and 11b6d47

**Comment by schontz** [comment]
That was quick! This will be in 4.4.3?

**Comment by jason0x43** [comment]
Yes
