### ISSUE TITLE
Query arguments not honored in serveOnly mode

### ISSUE THREAD

**Issue by schontz** [theintern/intern#991]
## Expected behavior
Run intern in serveOnly mode without plugins via `http://localhost:9000/__intern/?plugins=`

## Current behavior
`Error initializing Intern: Error: Non-object value "true" for plugins`

## Steps to reproduce

1. Add a plugin to `intern.json`, e.g.:
```json
"plugins": {
	"script": "@theintern/visual-plugin",
	"options": { "missingBaseline": "snapshot"}
}
```

2. Run `npx intern serveOnly`
3. Visit `http://localhost:9000/__intern/`. Page is blank because plugin fails to load (404).
4. Visit `http://localhost:9000/__intern/?plugins=`. Page is blank because query string is not parsed properly (see above error message).

## Environment

Intern version: 4.4.3
Node version: 10.14.1
NPM version: 6.9.2
Platform: Windows

**Comment by jason0x43** [comment]
It looks like the last update to the query arg processing code, which switched from custom processing to URLSearchParams, changed how query args with no value, like `plugins=`, are handled. Query args are normalized and processed with the same logic as command line args. Previously, a query arg like `plugins=` was parsed with that form, but currently such args are normalized to `plugins`, which is treated as a boolean arg by the arg parsing code.

We'll need to move back to something more custom to maintain query arg and cli equivalence since URL search params don't natively distinguish between `plugins` and `plugins=`.
